require: rubocop-rails

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 120

Metrics/AbcSize:
  Max: 25